---
abstract: 'STHEBERT Dist Zilla plugin bundle'
author:
  - 'Sebastien Thebert <stt@onetool.pm>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-STHEBERT
provides:
  Dist::Zilla::PluginBundle::Author::STHEBERT:
    file: lib/Dist/Zilla/PluginBundle/Author/STHEBERT.pm
    version: '0.2'
requires:
  Moose: '0'
  perl: '5.006'
resources:
  repository: https://github.com/sebthebert/Dist-Zilla-PluginBundle-Author-STHEBERT.git
version: '0.2'
